### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by moscicki** [apsknight/gangaextension#6]
This happens where there is no kerberos ticket. 

Problem 1: unhandled exception
Problem 2: it will likely cause the subsequent cell to hang forever

Correct behaviour should be: error message to the user, job not submitted (in new state).

Please check if you get the same problem with unhandled exception on Ganga without your modification.

￼
![image](https://user-images.githubusercontent.com/621965/43320296-53f588f0-91a8-11e8-96ce-239019b00c1a.png)

![image](https://user-images.githubusercontent.com/621965/43320307-5c635d96-91a8-11e8-96ea-d054ca9d199f.png)

**Comment by apsknight** [comment]
Getting similar error in Ganga (without any modifications) also.

```python
INFO     submitting job 50
INFO     job 50 status changed to "submitting"
INFO     Preparing Executable application.
INFO     Created shared directory: conf-79faf261-3780-407f-a2c0-7629ef9433ec
INFO     Preparing subjobs
ERROR    Tried submitting job with command: 'condor_submit -v /root/gangadir/workspace/root/LocalXML/50/input/./__cdf__'
ERROR    Return code: 256
ERROR    Condor output:
ERROR    
ERROR: Submitting jobs as user/group 0 (root) is not allowed for security reasons.
ERROR    Parallel Job Submission Failed: IncompleteJobSubmissionError: ('50', 'submission failed')
INFO     job 50 status changed to "new"
WARNING  Not all subjobs have been sucessfully submitted: IncompleteJobSubmissionError: (['50'], "submission failed for subjobs ['50']")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/ganga/ganga/GangaCore/GPIDev/Base/Proxy.py", line 709, in proxy_wrapped
    r = f(*s_args, **s_kwargs)
  File "/root/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 1557, in submit
    self.updateStatus('failed')
  File "/root/ganga/ganga/GangaCore/GPIDev/Lib/Job/Job.py", line 570, in updateStatus
    raise JobStatusError('forbidden status transition of job %s from "%s" to "%s"' % (fqid, initial_status, newstatus))
GangaCore.GPIDev.Lib.Job.Job.JobStatusError: JobStatusError: forbidden status transition of job 50 from "new" to "failed"
```
![screenshot from 2018-07-31 23-32-46](https://user-images.githubusercontent.com/19551774/43478082-8a90a140-951a-11e8-8dcd-025ac5ddf046.png)

**Comment by apsknight** [comment]
Issue opened on Ganga repo: ganga-devs/ganga#1316
